### ISSUE TITLE
smk rev a3 led407 

### ISSUE THREAD

**Issue by anthonysymak** [4pplet/Steezy60#1]
led not work due to GND not connected.   attached photo showing remedy.
![image0](https://user-images.githubusercontent.com/30567691/97552150-dc21d080-1a0e-11eb-9d60-d7b3dda0919e.jpeg)

**Comment by 4pplet** [comment]
Thanks for showing interest in the project! :) 

Did you use the files from the release? My guess is that your PCB has a faulty VIA shown below.
![Screenshot 2020-10-29 at 11 36 22](https://user-images.githubusercontent.com/710704/97574004-df0aca00-19ea-11eb-83a4-3eb0721e4ae9.png)

I have made PCB's using the files in the release A3 and have no issues with LED407
![IMG_4124](https://user-images.githubusercontent.com/710704/97574505-a0294400-19eb-11eb-9ef0-2df2cb304e36.jpg)

**Comment by anthonysymak** [comment]
Hi, thanks for reply, I do use the release.  but not a big issue.  Just
report to the property owner.

Thanks again.

Anthony

**Comment by anthonysymak** [comment]
for your informtion, I downloaded the release on Oct 8.  

Thank you

**Comment by 4pplet** [comment]
Thanks for reporting it, hope you are happy with the board! :) Closing the issue
